arch_package_manager = "yay"

hostname_groups_enabled = true

flatpak_systemwide = true



[hostname_groups]
archlinux = [
    "arch/base.toml",
    "arch/xorg.toml",
]
ubuntu = [
    "ubuntu/base.toml"
]
fedora = [
    "fedora/base.toml"
]
