-- You can add your own plugins here or in other files in this directory!
--  I promise not to create any merge conflicts in this directory :)
--
-- See the kickstart.nvim README for more information
return {
  -- 'nvim-lua/plenary.nvim',
  -- { 'nvim-tree/nvim-web-devicons', lazy = true },
  --
  -- {
  --   'nvchad/ui',
  --   config = function()
  --     require 'nvchad'
  --   end,
  -- },
  --
  -- {
  --   'nvchad/base46',
  --   lazy = true,
  --   build = function()
  --     require('base46').load_all_highlights()
  --   end,
  -- },
}
