return {

  -- {
  --   "echasnovski/mini.operators",
  --   version = "*",
  --   config = function()
  --     require("mini.operators").setup({
  --       exchange = {
  --         prefix = "gz",
  --         reindent_linewise = true,
  --       },
  --       replace = {
  --         prefix = "g<",
  --         reindent_linewise = true,
  --       },
  --     })
  --   end,
  -- },
  -- {
  --   "echasnovski/mini.files",
  --   opts = {
  --     options = {
  --       use_as_default_explorer = true,
  --     },
  --   },
  --   keys = {
  --     {
  --       "<leader>e",
  --       function()
  --         require("mini.files").open(vim.api.nvim_buf_get_name(0), true)
  --       end,
  --       desc = "Open mini.files (directory of current file)",
  --     },
  --     {
  --       "<leader>E",
  --       function()
  --         require("mini.files").open(vim.fn.getcwd(), true)
  --       end,
  --       desc = "Open mini.files (cwd)",
  --     },
  --     {
  --       "<leader>fm",
  --       function()
  --         require("mini.files").open(LazyVim.root(), true)
  --       end,
  --       desc = "Open mini.files (root)",
  --     },
  --   },
  -- },
}
